### ISSUE TITLE
Lines should break between words

### ISSUE THREAD

**Issue by VFDan** [vBread/bd-contributions#8]
**A clear description of the issue**
Line breaks currently can happen in the middle of a word if the lines are too long. This can look ugly and breaks the reader's flow. Lines should break _between_ words so the flow is undisturbed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44413950/115642056-47769c00-a2e8-11eb-9bb9-8293c7bd0d91.png)

**Additional info**
- Codeblock language, if any: Shouldn't matter, but testing with none
- Discord build & version: Stable 82866 (d02d7ca)
- Platform: Windows 10 64-Bit (10.0.18362)
- Plugin version: 1.2.0

**Comment by Ascor8522** [comment]
https://github.com/xiBread/bd-contributions/blob/1be95b118ae78f3f46941df24c68403de9533e86/BetterCodeblocks/BetterCodeblocks.plugin.js#L441-L444

should be
```css
.bd-codeblock-table td:last-child { 
    padding-left: 8px; 
    word-break: break-word;
} 
```

**Comment by Glaived** [comment]
thank you @Ascor8522 

To fix the problem via a temporary solution, using CSS injection:
```css
.bd-codeblock-table td:last-child { 
    word-break: break-word !important;
} 
```
